<?php
    class Ibarah_model extends CI_MODEL{
        public function kalimat(){
            $data = [
                $this->data_kalimat("", "1", "أَنَا جُوْعَانُ", "Saya lapar"),
                $this->data_kalimat("", "1", "أَنَا شَبْعانُ", "Saya kenyang"),
                $this->data_kalimat("", "1", "أَنَا مُرْتَبِكٌ", "Saya gerogi"),
                $this->data_kalimat("", "1", "أَنَا مُوافِقٌ", "Saya setuju"),
                $this->data_kalimat("", "1", "أَنَا زَعْلانُ", "Saya ngambek"),
                $this->data_kalimat("", "1", "أَنَا مُسْتَسْلِمٌ", "Saya menyerah"),
                $this->data_kalimat("", "1", "لَدَيَّ حُمَّي", "Saya demam"),
                $this->data_kalimat("", "1", "أَنَا سَرِيعُ النِسْيانِ", "Saya pelupa"),
                $this->data_kalimat("", "1", "أنْتَ كَسْلانُ", "Kamu pemalas"),
                $this->data_kalimat("", "1", "أَنَا مُجْتَهِدٌ جِدًّا", "Saya rajin banget"),
                $this->data_kalimat("", "1", "أَنَا مُتَأَثِّرٌ", "Saya tersentuh"),
                $this->data_kalimat("", "1", "أَنَا أَسْتَحْيِيْ", "Saya malu"),
                $this->data_kalimat("", "1", "أنْتَ مَهْزُوْمٌ", "Kamu kalah"),
                $this->data_kalimat("", "1", "أَنَا مُخْتَنِقٌ", "Saya sumpek"),
                $this->data_kalimat("", "1", "أنْتَ جَبَانٌ", "Kamu pengecut"),

                
                $this->data_kalimat("", "2", "أَنَا مُتَفاجِئٌ", "Saya kaget"),
                $this->data_kalimat("", "2", "أَنَا مُسْتَسْلِمٌ", "Saya kapok"),
                $this->data_kalimat("", "2", "أَنَا مُتَحَيِّرٌ", "Saya bingung"),
                $this->data_kalimat("", "2", "أَنَا مُتْعَبٌ جِدًّا", "saya capek banget"),
                $this->data_kalimat("", "2", "أَنَا زَلَّةُ لِسَانٍ", "Saya keceplosan"),
                $this->data_kalimat("", "2", "أنْتَ مَقْبُوضٌ", "Kamu tertangkap"),
                $this->data_kalimat("", "2", "أَنَا فُضُوْلِيٌّ", "Saya penasaran"),
                $this->data_kalimat("", "2", "أَنَا عَطْشانُ", "Saya haus"),
                $this->data_kalimat("", "2", "أَنَا رَاضِي", "Saya puas"),
                $this->data_kalimat("", "2", "أَنَا مُسْتَعْجِلٌ", "Saya terburu-buru"),
                $this->data_kalimat("", "2", "أَنَا مَصْدُوعٌ", "Saya pusing"),
                $this->data_kalimat("", "2", "أنْتَ بَطِيءٌ", "Saya lemot"),
                $this->data_kalimat("", "2", "أنا فائِزٌ", "Saya menang"),
                $this->data_kalimat("", "2", "أَنَا وَاثِقٌ  مِنْ نَفْسِيْ", "Saya PD"),
                $this->data_kalimat("", "2", "أنا جَادٌّ", "Saya serius"),

                $this->data_kalimat("", "3", "أنا مُحْبِطٌ", "Saya frustrasi"),
                $this->data_kalimat("", "3", "أنْتَ شُجَاعٌ", "Kamu pemberani"),
                $this->data_kalimat("", "3", "أَنَا خائِفٌ", "Saya takut"),
                $this->data_kalimat("", "3", "أنْتَ مُجْرِمٌ", "Kamu penjahat"),
                $this->data_kalimat("", "3", "أنْتَ عَجِيْبٌ", "Kamu ada-ada saja"),
                $this->data_kalimat("", "3", "أنْتَ مُتَوَحِّشٌ", "Kamu kejam"),
                $this->data_kalimat("", "3", "أَنَا مُتَأكِّدٌ", "Saya yakin"),
                $this->data_kalimat("", "3", "أَنَا مُرْتاحٌ هُنا", "Saya betah disini"),
                $this->data_kalimat("", "3", "أَنْتَ مُخْجِلٌ", "Kamu malu-maluin"),
                $this->data_kalimat("", "3", "أَنْتَ لَطِيْفٌ", "Kamu menggemaskan"),
                $this->data_kalimat("", "3", "أَنْتَ مُبالِغٌ", "Kamu lebay"),
                $this->data_kalimat("", "3", "أَنَا مُتَفَهِّمٌ", "Saya pengertian"),
                $this->data_kalimat("", "3", "أنتَ مُسْتَقِلٌّ", "Kamu mandiri"),
                $this->data_kalimat("", "3", "أَنْتَ أنانِيٌّ", "Kamu egois"),
                $this->data_kalimat("", "3", "أنتَ مُمْتِعٌ", "Kamu menyenangkan"),

                $this->data_kalimat("", "4", "ابْتَعِدْ عَنِ التَدْخِينِ قَدْرَ اْلإِمْكَانِ", "Jauhilah rokok sebisa mungkin!"),
                $this->data_kalimat("", "4", "قُلْ بِصَرَاحَةٍ", "Katakan dengan terus terang!"),
                $this->data_kalimat("", "4", "احْفَظُوْا ظَهْرًا عَنْ غَيْبٍ", "Hafalkan di luar kepala!"),
                $this->data_kalimat("", "4", "أَصْلِحْ غِلْطَتَكَ", "Perbaiki kesalahanmu!"),
                $this->data_kalimat("", "4", "مارِسْ لُغَتَكَ", "Praktekkan bahasamu!"),
                $this->data_kalimat("", "4", "أَيْقِظْنِيْ في الساعةِ الثالِثةِ صَبَاحًا", "Bangunkan saya jam tiga pagi!"),
                $this->data_kalimat("", "4", "أغْلِقِ البَابَ", "Tutup pintunya!"),
                $this->data_kalimat("", "4", "اُدْخُلْ فِي الطَّابُورِ", "Antri dong!"),
                $this->data_kalimat("", "4", "تَنَبَّهْ فِي الطَّرِيْقِ", "Hati-hati di jalan!"),
                $this->data_kalimat("", "4", "قَلِّدْ كَلامِي", "Ikuti ucapanku!"),

                $this->data_kalimat("", "5", "كَرِّرْ مَرَّةً ثَانِيةً", "Ulangi lagi!"),
                $this->data_kalimat("", "5", "مَرّةً أُخْرَى", "Sekali lagi!"),
                $this->data_kalimat("", "5", "اُبْسُطِ البِسَاطَ", "Bukalah karpetnya!"),
                $this->data_kalimat("", "5", "اِطْوِ البِساطَ", "Lipatlah karpetnya!"),
                $this->data_kalimat("", "5", "اِحْذَرْ", "Awas!"),
                $this->data_kalimat("", "5", "نَبِّهْنِي", "Ingatkan saya!"),
                $this->data_kalimat("", "5", "صَفِّقُوا", "Tepuk tangan!"),
                $this->data_kalimat("", "5", "أطْفِئِ اللَّمْبَةَ", "Matikan lampu!"),
                $this->data_kalimat("", "5", "اِفْتَحِ اللَّمْبَةَ", "Nyalakan lampu!"),
                $this->data_kalimat("", "5", "اِغْتَسِلْ أوَّلا", "Mandi dulu!"),
                $this->data_kalimat("", "5", "مِنْ فَضْلِكَ", "Tolong!"),
                $this->data_kalimat("", "5", "اُحْضُرْ لِيْ الكِتَابَ", "Ambilkan saya buku!"),
                $this->data_kalimat("", "5", "اِفْتَحِ البَابَ", "Bukalah pintunya!"),
                $this->data_kalimat("", "5", "شَارِكْ مَعِي", "Ikutlah bersamaku!"),
                $this->data_kalimat("", "5", "نَظِّفْ غُرْفَتَكَ", "Bersihkan kamarmu!"),

                $this->data_kalimat("", "6", "اُكْنُسِ السَّاحَةَ", "Sapulah halamannya!"),
                $this->data_kalimat("", "6", "اِنْتَظِرْ لَحْظَةً", "Tunggu sebentar!"),
                $this->data_kalimat("", "6", "اُدْعُ لي", "Doakan saya!"),
                $this->data_kalimat("", "6", "تَفَضَّلْ عِنْدِيْ", "Silahkan mampir!"),
                $this->data_kalimat("", "6", "تَوَقَّفْ عِنْدَنَا", "Silahkan mampr!"),
                $this->data_kalimat("", "6", "أَنَا مُنْتَعِشٌ", "Aku merasa segar"),
                $this->data_kalimat("", "6", "شَعُرْتُ بِالدَّغْدَغَةِ", "Aku merasa geli"),
                $this->data_kalimat("", "6", "شَعُرْتُ بِالْـجُوْعِ", "Aku merasa lapar"),
                $this->data_kalimat("", "6", "شَعُرْتُ بِالْمَلَلِ", "Aku merasa bosan"),
                $this->data_kalimat("", "6", "شَعُرْتُ بِالغِيْرَةِ", "Aku merasa cemburu"),
                $this->data_kalimat("", "6", "شَعُرْتُ بِاْلألَمِ فِي كُلِّ جَسَدِيْ", "Aku merasa sakit di seluruh badan"),
                $this->data_kalimat("", "6", "اِشْتَرِ لي رَصيدًا", "Belikan saya pulsa!"),
                $this->data_kalimat("", "6", "أَنْهِ الطَّعَامَ", "Habiskan makanannya!"),
                $this->data_kalimat("", "6", "أَبْطِئْ فِي مَشْيِكَ", "Pelan-pelan dong jalannya!"),
                $this->data_kalimat("", "6", "أَسْرِعْ في مَشْيِكَ", "Cepetan dong jalannya!"),

                $this->data_kalimat("", "7", "خَيْرٌ لَكَ أَنْ تَسْكُتَ", "Sebaiknya kamu diam"),
                $this->data_kalimat("", "7", "دَعْنِي أَنْ أَسْتَرِيْحَ أوَّلًا", "Biarkan saya beristirahat"),
                $this->data_kalimat("", "7", "اِبْتَعِدْ عَنِّيْ", "Menjauhlah dariku! "),
                $this->data_kalimat("", "7", "اِقْتَرِبْ مِنِّي", "Mendekatlah denganku!"),
                $this->data_kalimat("", "7", "مَاذَا أَصَابَكَ ؟", "Kamu sakit apa?"),
                $this->data_kalimat("", "7", "أَصَابَنِيَ الإسْهَالُ", "Saya sakit mencret"),
                $this->data_kalimat("", "7", "أَصَابَنِيَ الحُمَّى", "Saya sakit demam"),
                $this->data_kalimat("", "7", "أَصَابَنِيَ الزُّكَامُ", "Saya pilek"),
                $this->data_kalimat("", "7", "أصابَنِيَ القُلَاعُ", "Saya sakit sariawan"),
                $this->data_kalimat("", "7", "أصابَنِيَ الدُّمَلُ", "Saya bisulan"),
                $this->data_kalimat("", "7", "أصابَنِيَ السُّعالُ", "Saya batuk"),
                $this->data_kalimat("", "7", "مَعِيَ مَغْصٌ", "Saya sakit perut"),
                $this->data_kalimat("", "7", "هَلْ  شُفِيْتَ ؟", "Apa kamu sudah sembuh?"),
                $this->data_kalimat("", "7", "شَفاك اللهُ", "Semoga cepat sembuh"),
                $this->data_kalimat("", "7", "الحَمْدُ للهِ تَحَسَّنْتُ قَلِيْلًا", "Alhamdulillah agak lebih baik"),

                $this->data_kalimat("", "8", "اِرْفَعْ صَوْتَكَ", "Keraskan suaramu!"),
                $this->data_kalimat("", "8", "اِخْفِضْ صَوْتَكَ", "Pelankan suaramu!"),
                $this->data_kalimat("", "8", "تَكَلَّمْ بِصَوتٍ مُنْخَفِضٍ", "Bicaralah dengan suara pelan!"),
                $this->data_kalimat("", "8", "خُذْ راحَتَكَ", "Santai aja lagi!"),
                $this->data_kalimat("", "8", "اِبْتَعِدْ قَلِيْلًا", "Geser sedikit!"),
                $this->data_kalimat("", "8", "تَقَدَّمْ قَلِيْلًا", "Maju sedikit!"),
                $this->data_kalimat("", "8", "اِرْجِعْ قَلِيْلًا", "Mundur sedikit!"),
                $this->data_kalimat("", "8", "مَرَضٌ وَرَاثِيٌّ", "Penyakit keturunan"),
                $this->data_kalimat("", "8", "مَرَضٌ مُعْدِي", "Penyakit menular"),
                $this->data_kalimat("", "8", "هَلْ قَابَلْتَ الطَّبِيْبَ ؟", "Apakah kamu sudah ke dokter?"),
                $this->data_kalimat("", "8", "شَعُرْتُ بِالْوَحْدَةِ", "Aku merasa kesepian"),
                $this->data_kalimat("", "8", "شَعُرْتُ بِالبُرُوْدَةِ", "Aku merasa kedinginan"),
                $this->data_kalimat("", "8", "شَعُرْتُ بِالْحَرَارَةِ", "Aku merasa kepanasan"),
                $this->data_kalimat("", "8", "هَذِهِ اللَّيْلَةَ", "Nanti malam"),
                $this->data_kalimat("", "8", "لَيْلَةَ أَمْسِ", "Kemarin malam"),

                $this->data_kalimat("", "9", "هَذِهِ فِكْرَةٌ جَيِّدَةٌ", "Ini ide bagus"),
                $this->data_kalimat("", "9", "تَفَضَّلْ", "Silahkan"),
                $this->data_kalimat("", "9", "مِنْ فَضْلِكَ", "Silahkan"),
                $this->data_kalimat("", "9", "عِلَاوَةً عَلَى ذَلِكَ", "Apalagi"),
                $this->data_kalimat("", "9", "أَثْنَاءَ الدِّرَاسَةِ", "Tengah pelajaran"),
                $this->data_kalimat("", "9", "فَقَطْ/ فَحَسْبُ", "Saja"),
                $this->data_kalimat("", "9", "رُبَّـمَـا", "Barangkali"),
                $this->data_kalimat("", "9", "لَا بَأْسَ/ لَا شَيْءَ", "Gak apa-apa"),
                $this->data_kalimat("", "9", "لَا أَحَدَ", "Tak seorangpun"),
                $this->data_kalimat("", "9", "مُهِمٌّ جِدًّا", "Penting banget"),
                $this->data_kalimat("", "9", "أَيْضًا", "Juga"),
                $this->data_kalimat("", "9", "نَعَمْ، حَاضِرْ", "Iya"),
                $this->data_kalimat("", "9", "شُكْرًا جَزِيْلاً", "Terima kasih banyak"),
                $this->data_kalimat("", "9", "عَفْوًا", "Maaf"),
                $this->data_kalimat("", "9", "آسِفْ/ مَعْذِرَةً/ عَفْوًا", "Permisi"),

                $this->data_kalimat("", "10", "طَيِّبْ، حَسَنًا", "ok"),
                $this->data_kalimat("", "10", "حَقًّا/ أَكِيْد", "Sungguh"),
                $this->data_kalimat("", "10", "فِي الحَقِيْقَةِ", "Sebenarnya"),
                $this->data_kalimat("", "10", "طَبْعًا", "Tentu"),
                $this->data_kalimat("", "10", "بِلاَ شَكٍّ", "Dengan tanpa ragu"),
                $this->data_kalimat("", "10", "مُؤَقَّتًا", "Sementara"),
                $this->data_kalimat("", "10", "مَرَّةً أُخْرَى", "Sekali lagi"),
                $this->data_kalimat("", "10", "بِالتَّدْرِيْجِ", "Secara bertahap"),
                $this->data_kalimat("", "10", "شَيْئًا فَشَيْئًا", "Sedikit demi sedikit"),
                $this->data_kalimat("", "10", "قَلِيْلاً فَقَلِيْلاً", "Sedikit demi sedikit"),
                $this->data_kalimat("", "10", "حَتَّى الآنَ", "Hingga sekarang"),
                $this->data_kalimat("", "10", "بِالتَّأَنِّي", "Pelan-pelan"),
                $this->data_kalimat("", "10", "عَلَى مَسْؤُوْلِيَتِيْ", "Tanggung jawabku"),
                $this->data_kalimat("", "10", "عَلَى حِسَابِيْ", "Saya yang traktir"),
                $this->data_kalimat("", "10", "عِلَاوَةً عَلَى هَذَا", "Apalagi ini"),

                $this->data_kalimat("", "11", "خُصُوْصًا هَذَا", "Khususnya ini"),
                $this->data_kalimat("", "11", "بِسُهُوْلَةٍ", "Dengna mudah"),
                $this->data_kalimat("", "11", "بِصُعُوْبَةٍ", "Dengan sulit"),
                $this->data_kalimat("", "11", "عَلَى فَرْحَتِكْ/ كَمَا شِئْتَ", "Terserah kamu"),
                $this->data_kalimat("", "11", "بِهَذِهِ الطَّرِيْقَةِ", "Dengan cara ini"),
                $this->data_kalimat("", "11", "بِدُوْنِ  اسْتِثْنَاءٍ", "Tanpa terkecuali"),
                $this->data_kalimat("", "11", "هَكَذَا", "Begini lo"),
                $this->data_kalimat("", "11", "هَذَا مُـمْكِنٌ", "Ini mungkin"),
                $this->data_kalimat("", "11", "هَذَا أَحْسَنُ", "Ini bagus"),
                $this->data_kalimat("", "11", "هَذَا شَيْءٌ ظَاهِرٌ", "Ini sesuatu yang nampak"),
                $this->data_kalimat("", "11", "لَاتُشْغِلْ نَفْسَكْ", "Jangan repot-repot"),
                $this->data_kalimat("", "11", "بِقَدْرِ الاِسْتِطَاعَةِ", "Sebisanya"),
                $this->data_kalimat("", "11", "بِقَدْرِ الاِمْكَانِ", "Sebisa mungkin"),
                $this->data_kalimat("", "11", "لاَ تَسْتَعْجِلْ", "Jangan terburu-buru"),
                $this->data_kalimat("", "11", "مَا أَجْمَلَهُ", "Betapa gantengnya dia"),

                
                $this->data_kalimat("", "12", "عَلَى مَا أَظُنُّ", "Seperti yang kukira"),
                $this->data_kalimat("", "12", "أَنَا مَشْغُولٌ", "Saya repot"),
                $this->data_kalimat("", "12", "هَذَا كَثِيْرٌ جِدًّا", "Ini banyak banget"),
                $this->data_kalimat("", "12", "رَأَيْتُهُ عِيَانًا", "Saya melihat sendiri"),
                $this->data_kalimat("", "12", "لاَ أَعْرِفُ ذَلِكَ", "Saya gak tahu itu"),
                $this->data_kalimat("", "12", "لاَ أُصَدِّقُ ذَلِكَ", "Saya gak percaya itu"),
                $this->data_kalimat("", "12", "مِنَ الآنَ فَصَاعِدًا", "Dari sekarang dan seterusnya"),
                $this->data_kalimat("", "12", "بِكُلِّ فَرَحٍ وَسُرُورٍ", "Dengan senang hati"),
                $this->data_kalimat("", "12", "بِدُوْنِ عَمْدٍ", "Tanpa sengaja"),
                $this->data_kalimat("", "12", "عَادَةً", "Biasanya "),
                $this->data_kalimat("", "12", "كَالعَادَةِ", "Seperti biasa"),
                $this->data_kalimat("", "12", "إِذَا أَمْكَنَ", "Jika mungkin"),
                $this->data_kalimat("", "12", "عَلَى الدَّوَامِ/ لِلْأَبَدِ", "Selamanya"),
                $this->data_kalimat("", "12", "غَالِبًا", "Sering"),
                $this->data_kalimat("", "12", "مِرَارًا", "Berkali-kali"),

                
                $this->data_kalimat("", "13", "لَا عَجَبَ", "Pantesan"),
                $this->data_kalimat("", "13", "مُتَأَسِّفٌ جِدًّا", "Kasihan banget"),
                $this->data_kalimat("", "13", "هَا قَدْ جَاءَ", "Ini dia dah datang"),
                $this->data_kalimat("", "13", "هَيَّا بِنَا نَخْرُجُ مَعًا", "Ayo keluar bareng"),
                $this->data_kalimat("", "13", "هَيَّا بِنَا نَسْتَرِيْحُ", "Ayo istirahat"),
                $this->data_kalimat("", "13", "أَيْنَ عُنْوَانُكَ", "Mana alamatmu"),
                $this->data_kalimat("", "13", "غَدًا أَوْ بَعْدَ غَدٍ", "Besok atau besok lusa"),
                $this->data_kalimat("", "13", "هَذَا الخَـبَرُ صَحِيْحٌ", "Berita ini benar"),
                $this->data_kalimat("", "13", "هَذَا الخَـبَرُ  زَائِفٌ", "Berita ini hoax"),
                $this->data_kalimat("", "13", "هَذَا أَمْرٌ مُهِمٌّ", "Ini hal penting"),
                $this->data_kalimat("", "13", "هَذَا أَمْرٌ  بَسِيْطٌ", "Ini hal  sepele"),
                $this->data_kalimat("", "13", "هَذَا عَجِيْبٌ جِدًّا", "Ini menakjubkan"),
                $this->data_kalimat("", "13", "لَكَ رِسَالَةٌ قَصِيْرَةٌ", "Kamu dapat sms ni"),
                $this->data_kalimat("", "13", "اُنْظُرْ اِلَيَّ", "Lihat saya"),
                $this->data_kalimat("", "13", "اِهْتَمُّوْا جَيِّدًا", "Perhatikan baik-baik"),

                
                $this->data_kalimat("", "14", "أُحِبُّكَ", "Saya cinta kamu"),
                $this->data_kalimat("", "14", "لَا تَنْسَ", "Jangan lupa"),
                $this->data_kalimat("", "14", "مَا عِنْدِيْ وَقْتٌ", "Saya gak punya waktu"),
                $this->data_kalimat("", "14", "لَـمْ أَفْهَمْ مَا تُرِيْدُ", "Saya gak ngerti apa yang kamu mau"),
                $this->data_kalimat("", "14", "أَحْتَاجُ إِلَى مُسَاعَدَتِكْ", "Saya butuh bantuanmu"),
                $this->data_kalimat("", "14", "أَنَا فَرْحَانُ بِمُقَابَلَتِكَ", "Saya senang bertemu denganmu"),
                $this->data_kalimat("", "14", "مُتَشَرِّفٌ بِـمَعْرِفَتِكْ", "Senang kenal denganmu"),
                $this->data_kalimat("", "14", "اِنْتَبِهْ", "Hati-hati"),
                $this->data_kalimat("", "14", "اِحْتَرِسْ", "Awas "),
                $this->data_kalimat("", "14", "هَلْ عِنْدَكَ حَبِيْبَةٌ ؟", "Apakah kamu punya kekasih?"),
                $this->data_kalimat("", "14", "مَازِلْتُ عَازِبًا", "Aku masih bujang"),
                $this->data_kalimat("", "14", "حَسَنًا جِدًّا", "Bagus banget"),
                $this->data_kalimat("", "14", "تَعَالْ بِسُرْعَةٍ", "Kesini ! cepat"),
                $this->data_kalimat("", "14", "لَا تَدْخُلْ قَبْلَ السَّلاَمِ", "Jangan masuk sebelum salam"),
                $this->data_kalimat("", "14", "تَقَدَّمْ إِلَى الأَمَامِ", "Maju kedepan"),
                
                $this->data_kalimat("", "15", "لَا تُدَغْدِغْنِيْ", "Jangan menggelitiki aku"),
                $this->data_kalimat("", "15", "لَا تَتَدَخَّلْ فِي أَمْرِيْ", "Jang ikut campur"),
                $this->data_kalimat("", "15", "لَا تَحْزَنْ", "Jangan sedih"),
                $this->data_kalimat("", "15", "لَا تَـخَفْ", "Jangan takut"),
                $this->data_kalimat("", "15", "لَا تَغْضَبْ", "Jangan marah"),
                $this->data_kalimat("", "15", "أَنْتَ مِسْكِيْنُ", "Kamu kasihan"),
                $this->data_kalimat("", "15", "لِمـَاذَا جِئْتَ مُتَأَخِّرًا", "Kenapa kamu terlambat"),
                $this->data_kalimat("", "15", "لَا تَمْزَحْ", "Jangan bercanda "),
                $this->data_kalimat("", "15", "لَا تُشَوِّشْ", "Jangan berisik "),
                $this->data_kalimat("", "15", "لَا تَكُنْ فُضُوْلِيًّا", "Jangan kepo deh"),
                $this->data_kalimat("", "15", "لَا تَرْمِ الزُّبَالَةِ فِي أَيِّ مَكَانٍ", "Jangan buang sampah sembarangan"),
                $this->data_kalimat("", "15", "كَمْ مَرَّةً؟", "Berapa kali"),
                $this->data_kalimat("", "15", "مَرَّتَيْنِ", "Dua kali"),
                $this->data_kalimat("", "15", "لاَ تَكُنْ كَذَلِكَ", "Jangan seperti itu"),
                $this->data_kalimat("", "15", "لَا تَفْعَلْ ذَلِكَ", "Jangan lakukan seperti itu"),
                
                $this->data_kalimat("", "16", "لَا تَضَعِ الأَشْيَاءَ هُنَا", "Jangan taruh sesuatu disini"),
                $this->data_kalimat("", "16", "لَا تَـحْتَقِرْ الآخَرِيْنَ", "Jangan menghina orang lain"),
                $this->data_kalimat("", "16", "لَا تَنْشُرْ الغِيْبَةَ", "Jangan sebar gosip"),
                $this->data_kalimat("", "16", "وَدَاعًا", "Selamat tinggal"),
                $this->data_kalimat("", "16", "أَنْتَ رَخِيْصٌ", "Kamu gak ada harganya"),
                $this->data_kalimat("", "16", "اُنْقُصْ قَلِيْلًا", "Kurangi dikit"),
                $this->data_kalimat("", "16", "اُنْظُرْ هُنَا", "Lihat sini"),
                $this->data_kalimat("", "16", "لاَشَيْءٍ", "Gak ada apa2"),
                $this->data_kalimat("", "16", "تَخَرَّجْتُ مِنْ", "Saya lulus dari"),
                $this->data_kalimat("", "16", "تَحَرَّكْ قَلِيْلاً", "Geser dikit dong"),
                $this->data_kalimat("", "16", "لاَ أُبَالِي/ لَا أَهْتَمُّ", "Saya gak peduli"),
                $this->data_kalimat("", "16", "نَفْسُ الشَّيْءِ", "Sama aja"),
                $this->data_kalimat("", "16", "إِلَى الِّلقَاءِ", "Sampai jumpa"),
                $this->data_kalimat("", "16", "مَعَ السَّلاَمَةِ", "Sampai jumpa"),
                $this->data_kalimat("", "16", "بِدُوْنِ تَفْكِيْرٍ", "Tanpa mikir"),
                
                $this->data_kalimat("", "17", "مُبَاشَرَةً", "Langsung "),
                $this->data_kalimat("", "17", "اِصْبِرْ يَا أَخِيْ", "Sabar bro"),
                $this->data_kalimat("", "17", "هَلْ تَسْمَعُ كَلَامِيْ", "Dengar ucapanku"),
                $this->data_kalimat("", "17", "هَلْ تَسْتَطِيْعُ أَنْ تُسَاعِدَنِى", "Apakah kamu bisa membantuku"),
                $this->data_kalimat("", "17", "هَيَّا تَعَالْ مَعِيْ", "Ayo ikut denganku"),
                $this->data_kalimat("", "17", "لَاتُزْعِجْنِيْ", "Jangan ganggu aku"),
                $this->data_kalimat("", "17", "لَا تُبْطِئْ", "Jangan lama-lama"),
                $this->data_kalimat("", "17", "أَنَا مُسْتَعِدٌّ", "Saya siap"),
                $this->data_kalimat("", "17", "أَنَا جَائِعٌ جِدًّا", "Saya lapar banget"),
                $this->data_kalimat("", "17", "أُسْكُتُوْا كُلَّكُمْ", "Kalian semua diam!"),
                $this->data_kalimat("", "17", "هَيَّا نَذْهَبُ مَعًا", "Ayo pergi bareng"),
                $this->data_kalimat("", "17", "رَائِعٌ جِدًّا", "Luar biasa sekali"),
                $this->data_kalimat("", "17", "لَاتَكْذِبْ عَلَيَّ", "Jangan bohongi aku"),
                $this->data_kalimat("", "17", "مَا عِنْدِيْ فُلُوْسٌ", "Aku gak punya uang"),
                $this->data_kalimat("", "17", "لَا اُرِيْدُ أَنْ اَسْمَعَ كَلَامَكْ", "Saya gak mau dengat ucapanku"),
                
                $this->data_kalimat("", "18", "لَا يُعْجِبُنْيْ كَثِيْرًا", "Saya gak terlalu suka"),
                $this->data_kalimat("", "18", "لَا تَقْلَقْ", "Jangan khawatir"),
                $this->data_kalimat("", "18", "لَا تُكَثِّرِ اْلكَلَامَ", "Jangan banyak ngomong "),
                $this->data_kalimat("", "18", "لَا تَدُرْ حَوْلَ الْمَوْضُوْعَ", "Jangan bertele-tele"),
                $this->data_kalimat("", "18", "أَحْتَاجُ الْمُسَاعَدَةْ", "Saya butuh bantuan"),
                $this->data_kalimat("", "18", "أَحْتَاجُ الرَّاحَةَ", "Saya butuh istirahat"),
                $this->data_kalimat("", "18", "حَقًّا اُرِيْدُ أَنْ أَذْهَبَ", "Saya benar2 pengen pergi"),
                $this->data_kalimat("", "18", "أَنَا أَمْزَحْ فَحَسْبُ", "saya hanya bercanda"),
                $this->data_kalimat("", "18", "يَجِبُ عَلَيَّ أَنْ أَذْهَبَ", "Saya harus pergi"),
                $this->data_kalimat("", "18", "لَا أُرِيْدُ أَنْ أَذْهَبَ اِلَى أَيِّ مَكَانٍ", "Saya tidak ingin pergi kemana-mana"),
                $this->data_kalimat("", "18", "هَذَا غَيْرُ مُرِيْحٍ", "Ini gak enak"),
                $this->data_kalimat("", "18", "اُتْرُكْنِيْ وَحْدِيْ", "Tinggalkan aku sendiri"),
                $this->data_kalimat("", "18", "جَرِّبْ أَوَّلًا", "Coba dulu "),
                $this->data_kalimat("", "18", "عِنْدِيْ مُشْكِلَةٌ كَبِيْرَةٌ", "Saya punya masalah besar"),
                $this->data_kalimat("", "18", "لَا تَكُنْ أَنَانِيًا", "Jangan egois"),

                $this->data_kalimat("", "19", "مَنْ سَارَ عَلىَ الدَّرْبِ وَصَلَ", "Barang siapa berjalan pada jalannya sampailah ia"),
                $this->data_kalimat("", "19", "مَنْ جَدَّ وَجَدَ", "Barang siapa bersungguh-sungguh, dapatlah ia"),
                $this->data_kalimat("", "19", "مَنْ صَبَرَ ظَفِرَ", "Barang siapa sabar beruntunglah ia"),
                $this->data_kalimat("", "19", "مَنْ قَلَّ صِدْقُهُ قَلَّ صَدِيْقُهُ", "Barang siapa sedikit benarnya/kejujurannya, sedikit pulalah temannya"),
                $this->data_kalimat("", "19", "جَالِسْ أَهْلَ الصِّدْقِ وَالوَفَاءِ", "Pergaulilah orang yang jujur dan menepati janji"),
                $this->data_kalimat("", "19", "مَوَدَّةُ الصَّدِيْقِ تَظْهَرُ وَقْتَ الضِّيْقِ", "Kecintaan/ketulusan teman itu, akan tampak pada waktu kesempitan"),
                $this->data_kalimat("", "19", "وَمَااللَّذَّةُ إِلاَّ بَعْدَ التَّعَبِ", "Tidak kenikmatan kecuali setelah kepayahan"),
                $this->data_kalimat("", "19", "الصَّبْرُ يُعِيْنُ عَلىَ كُلِّ عَمَلٍ", "Kesabaran itu menolong segala pekerjaan"),
                $this->data_kalimat("", "19", "جَرِّبْ وَلاَحِظْ تَكُنْ عَارِفًا", "Cobalah dan perhatikanlah, niscaya kau jadi orang yang tahu"),
                $this->data_kalimat("", "19", "اُطْلُبِ العِلْمَ مِنَ المَهْدِ إِلىَ اللَّحْدِ", "Tuntutlah ilmu sejak dari buaian hingga liang kubur"),
                $this->data_kalimat("", "19", "بَيْضَةُ اليَوْمِ خَيْرٌ مِنْ دَجَاجَةِ الغَدِ", "Telur hari ini lebih baik daripada ayam esok hari"),
                $this->data_kalimat("", "19", "الوَقْتُ أَثْمَنُ مِنَ الذَّهَبِ", "Waktu itu lebih mahal daripada emas"),

                $this->data_kalimat("", "20", "لعَقْلُ السَّلِيْمُ فيِ الجِسْمِ السَّلِيْمِ", "Akal yang sehat itu terletak pada badan yang sehat"),
                $this->data_kalimat("", "20", "يْرُ جَلِيْسٍ فيِ الزَّمَانِ كِتَابٌ", "Sebaik-baik teman duduk pada setiap waktu adalah buku"),
                $this->data_kalimat("", "20", "نْ يَزْرَعْ يَحْصُدْ", "Barang siapa menanam pasti akan memetik"),
                $this->data_kalimat("", "20", "خَيْرُ الأَصْحَابِ مَنْ يَدُلُّكَ عَلىَ الخَيْرِ", "Sebaik-baik teman itu ialah yang menunjukkan kamu kepada kebaikan"),
                $this->data_kalimat("", "20", "وْلاَ العِلْمُ لَكَانَ النَّاسُ كَالبَهَائِمِ", "Seandainya tiada berilmu niscaya manusia itu seperti binatang"),
                $this->data_kalimat("", "20", "العِلْمُ فيِ الصِّغَرِ كَالنَّقْشِ عَلىَ الحَجَرِ", "Ilmu pengetahuan diwaktu kecil itu, bagaikan ukiran di atas batu"),
                $this->data_kalimat("", "20", "نْ تَرْجِعَ الأَياَّمُ الَّتيِ مَضَتْ", "Tidak akan kembali hari-hari yang telah berlalu"),
                $this->data_kalimat("", "20", "تَعَلَّمْ صَغِيْرًا وَاعْمَلْ بِهِ كَبِيْرًا", "Belajarlah di waktu kecil dan amalkanlah di waktu besar"),
                $this->data_kalimat("", "20", "لعِلْمُ بِلاَ عَمَلٍ كَالشَّجَرِ بِلاَ ثَمَرٍ", "Ilmu tiada amalan bagaikan pohon tidak berbuah"),
                $this->data_kalimat("", "20", "الاتِّحَادُ أَسَاسُ النَّجَاحِ", "Bersatu adalah pangkal keberhasila"),
                $this->data_kalimat("", "20", "لاَ تَحْتَقِرْ مِسْكِيْنًا وَكُنْ لَهُ مُعِيْناً", "Jangan engkau menghina orang miskin bahkan jadilah penolong baginya"),
                $this->data_kalimat("", "20", "لشَّرَفُ بِالأَدَبِ لاَ بِالنَّسَبِ", "Kemuliaan itu dengan adab kesopanan, (budi pekerti) bukan dengan keturunan"),
                
                $this->data_kalimat("", "21", "سَلاَمَةُ الإِنْسَانِ فيِ حِفْظِ اللِّسَانِ", "Keselamatan manusia itu dalam menjaga lidahnya (perkataannya)"),
                $this->data_kalimat("", "21", "آدَابُ المَرْءِ خَيْرٌ مِنْ ذَهَبِهِ", "Adab seseorang itu lebih baik (lebih berharga) daripada emasnya"),
                $this->data_kalimat("", "21", "سُوْءُ الخُلُقِ يُعْدِي", "Kerusakan budi pekerti/akhlaq itu menular"),
                $this->data_kalimat("", "21", "آفَةُ العِلْمِ النِّسْياَنُ", "Bencana ilmu itu adalah lupa"),
                $this->data_kalimat("", "21", "إِذَا صَدَقَ العَزْمُ وَضَحَ السَّبِيْلُ", "Jika benar kemauannya niscaya terbukalah jalannya"),
                $this->data_kalimat("", "21", "لاَ تَحْتَقِرْ مَنْ دُوْنَكَ فَلِكُلِّ شَيْئٍ مَزِيَّةٌ", "Jangan menghina seseorang yang lebih rendah daripada kamu, karena segala sesuatu itu mempunyai kelebihan "),
                $this->data_kalimat("", "21", "أَصْلِحْ نَفْسَكَ يَصْلُحْ لَكَ النَّاسُ", "Perbaikilah dirimu sendiri, niscaya orang-orang lain akan baik padamu"),
                $this->data_kalimat("", "21", "فَكِّرْ قَبْلَ أَنْ تَعْزِمَ", "Berpikirlah dahulu sebelum kamu berkemauan"),
                $this->data_kalimat("", "21", "مَنْ عَرَفَ بُعْدَ السَّفَرِ اِسْتَعَدَّ", "Barang siapa tahu jauhnya perjalanan, bersiap-siaplah ia"),
                $this->data_kalimat("", "21", "مَنْ حَفَرَ حُفْرَةً وَقَعَ فِيْهَا", "Barang siapa menggali lobang, akan terperosoklah ia di dalamnya"),
                $this->data_kalimat("", "21", "عَدُوٌّ عَاقِلٌ خَيْرٌ مِنْ صَدِيْقٍ جَاهِلٍ", "Musuh yang pandai, lebih baik daripada tenan yang bodoh"),
                
                $this->data_kalimat("", "22", "مَنْ كَثُرَ إِحْسَانُهُ كَثُرَ إِخْوَانُهُ", "Barang siapa banyak perbuatan baiknya, banyak pulalah temannya"),
                $this->data_kalimat("", "22", "اِجْهَدْ وَلاَ تَكْسَلْ وَلاَ تَكُ غَافِلاً فَنَدَامَةُ العُقْبىَ لِمَنْ يَتَكاَسَلُ", "Bersungguh-sungguhlah dan jangan bermala-malas dan jangan pula lengah, karena penyesalan itu bagi orang yang bermalas-malas"),
                $this->data_kalimat("", "22", "لاَ تُؤَخِّرْ عَمَلَكَ إِلىَ الغَدِ مَا تَقْدِرُ أَنْ تَعْمَلَهُ اليَوْمَ", "Janganlah mengakhirkan pekerjaanmu hingga esok hari, yang kamu dapat mengejakannya hari ini"),
                $this->data_kalimat("", "22", "اُتْرُكِ الشَّرَّ يَتْرُكْكَ", "Tinggalkanlah kejahatan, niscaya ia (kejahatan itu) akan meninggalkanmu"),
                $this->data_kalimat("", "22", "خَيْرُ النَّاسِ أَحْسَنُهُمْ خُلُقاً وَأَنْفَعُهُمْ لِلنَّاسِ", "Sebaik-baik manusia itu, adalah yang terlebih baik budi pekertinya dan yang lebih bermanfaat bagi manusia"),
                $this->data_kalimat("", "22", "فيِ التَّأَنِّي السَّلاَمَةُ وَفيِ العَجَلَةِ النَّدَامَةُ", "Di dalam hati-hati itu adanya keselamatan, dan di dalam tergesa-gesa itu adanya penyesalan"),
                $this->data_kalimat("", "22", "ثَمْرَةُ التَّفْرِيْطِ النَّدَامَةُ وَثَمْرَةُ الحَزْمِ السَّلاَمَةُ", "Buah sembrono/lengah itu penyesalan, dan buah cermat itu keselamatan"),
                $this->data_kalimat("", "22", "الرِّفْقُ بِالضَّعِيْفِ مِنْ خُلُقِ الشَّرِيْفِ", "Berlemah lembut kepada orang yang lemah itu, adalah suatu perangai orang yang mulia"),
                $this->data_kalimat("", "22", "فَجَزَاءُ سَيِّئَةٍ سَيِّئَةٌ مِثْلُهَا", "Pahala/imbalan suatu kejahatan itu adalah kejahatan yang sama dengannya"),
                
                $this->data_kalimat("", "23", "تَرْكُ الجَوَابِ عَلىَ الجَاهِلِ جَوَابٌ", "Tidak menjawab terhadap orang yang bodoh itu adalah jawabannya"),
                $this->data_kalimat("", "23", "مَنْ عَذُبَ لِسَانُهُ كَثُرَ إِخْوَانُهُ", "Barang siapa manir tutur katanya (perkataannya) banyaklah temannya"),
                $this->data_kalimat("", "23", "إِذَا تَمَّ العَقْلُ قَلَّ الكَلاَمُ", "Apabila akal seseorang telah sempurna maka sedikitlah bicaranya"),
                $this->data_kalimat("", "23", "مَنْ طَلَبَ أَخًا بِلاَ عَيْبٍ بَقِيَ بِلاَ أَخٍ", "Barang siapa mencari teman yang tidak bercela, maka ia akan tetap tidak mempunyai teman"),
                $this->data_kalimat("", "23", "قُلِ الحَقَّ وَلَوْ كَانَ مُرًّا", "Katakanlah yang benar itu, walaupun pahit"),
                $this->data_kalimat("", "23", "خَيْرُ مَالِكَ مَا نَفَعَكَ", "Sebaik-baik hartamu adalah yang bermanfaat bagimu"),
                $this->data_kalimat("", "23", "خَيْرُ الأُمُوْرِ أَوْسَطُهَا", "Sebaik-baik perkara itu adalah pertengahanya"),
                $this->data_kalimat("", "23", "لِكُلِّ مَقَامٍ مَقَالٌ وَلِكُلِّ مَقَالٍ مَقَامٌ", "Tiap-tiap tempat ada kata-katanya yang tepat, dan pada setiap kata ada tempatnya yang tepat"),
                $this->data_kalimat("", "23", "إِذاَ لمَ ْ تَسْتَحْيِ فَاصْنَعْ مَا شِئْتَ", "Apabila engkau tidak malu, maka berbuatlah sekehendakmu"),
                $this->data_kalimat("", "23", "لَيْسَ العَيْبُ لِمَنْ كَانَ فَقِيْرًا بَلِ العَيْبُ لِمَنْ كَانَ بَخِيْلاً", "Bukanlah cela itu bagi orang yang miskin, tapi cela itu terletak pada orang yang kikir"),
                $this->data_kalimat("", "23", "لَيْسَ اليَتِيْمُ الَّذِي قَدْ مَاتَ وَالِدُهُ بَلِ اليَتِيْمُ يَتِيْمُ العِلْمِ وَالأَدَبِ", "Bukanlah anak yatim itu yang telah meninggal orang tuanya, tapi (sebenarnya) yatim itu adalah yatim ilmu dan budi pekerti"),
                
                $this->data_kalimat("", "24", "لِكُلِّ عَمَلٍ ثَوَابٌ وَلِكُلِّ كَلاَمٍ جَوَابٌ", "Setiap pekerjaan itu ada upahnya, dan setiap perkataan itu ada jawabannya"),
                $this->data_kalimat("", "24", "وَعَامِلِ النَّاسَ بِمَا تُحِبُّ مِنْهُ دَائِماً", "Dan pergaulilah manusia itu dengan apa-apa yang engkau sukai daripada mereka semuanya"),
                $this->data_kalimat("", "24", "هَلَكَ امْرُؤٌ لَمْ يَعْرِفْ قَدْرَهُ", "Hancurlah seseorang yang tidak tahu dirinya sendiri"),
                $this->data_kalimat("", "24", "رَأْسُ الذُّنُوْبِ الكَذِبُ", "Pokok dosa itu, adalah kebohongan"),
                $this->data_kalimat("", "24", "مَنْ ظَلَمَ ظُلِمَ", "Barang siapa menganiaya niscaya akan dianiaya"),
                $this->data_kalimat("", "24", "لَيْسَ الجَمَالُ بِأَثْوَابٍ تُزَيِّنُنُا إِنَّ الجَمَالَ جمَاَلُ العِلْمِ وَالأَدَبِ", "Bukanlah kecantikan itu dengan pakaian yang menghias kita, sesungguhnya kecantikan itu ialah kecantikan dengan ilmu dan kesopanan"),
                $this->data_kalimat("", "24", "لاَ تَكُنْ رَطْباً فَتُعْصَرَ وَلاَ يَابِسًا فَتُكْسَرَ", "Janganlah engkau bersikap lemah, sehingga kamu akan diperas, dan janganlah kamu bersikap keras, sehingga kamu akan dipatahkan"),
                $this->data_kalimat("", "24", "مَنْ أَعاَنَكَ عَلىَ الشَّرِّ ظَلَمَكَ", "Barang siapa menolongmu dalam kejahatan maka ia telah menyiksamu"),          
            ];

            return $data;
        }

        public function data_kalimat($id, $tema, $kalimat, $arti){
            $data = [
                "id" => $id,
                "tema" => $tema,
                "kalimat" => $kalimat,
                "arti" => $arti,
                "kata_arab" => array_unique($this->kata($kalimat)),
                "kata_indo" => array_unique($this->kata($arti)),
                "status" => "on"
            ];

            return $data;
        }

        public function kata($kata){
            $kata = explode(" ", $kata);
            // $kata[] = "_";
            return $kata;
        }

        public function tema(){
            $data = [
                $this->data_tema("1", "", "1", "2", "الحصة الأولى", "Bagian 1", "15"),
                $this->data_tema("1", "1", "2", "3", "الحصة الثانية", "Bagian 2", "15"),
                $this->data_tema("1", "2", "3", "4", "الحصة الثالثة", "Bagian 3", "15"),
                $this->data_tema("1", "3", "4", "5", "الحصة الرابعة", "Bagian 4", "10"),
                $this->data_tema("1", "4", "5", "6", "الحصة الخامسة", "Bagian 5", "15"),
                $this->data_tema("1", "5", "6", "7", "الحصة السادسة", "Bagian 6", "15"),
                $this->data_tema("1", "6", "7", "8", "الحصة السابعة", "Bagian 7", "15"),
                $this->data_tema("1", "7", "8", "9", "الحصة الثامنة", "Bagian 8", "15"),
                $this->data_tema("1", "8", "9", "10", "الحصة التاسعة", "Bagian 9", "15"),
                $this->data_tema("1", "9", "10", "11", "الحصة العاشرة", "Bagian 10", "15"),
                $this->data_tema("1", "10", "11", "12", "الحصة الحادية عشرة", "Bagian 11", "15"),
                $this->data_tema("1", "11", "12", "13", "الحصة الثانية عشرة", "Bagian 12", "15"),
                $this->data_tema("1", "12", "13", "14", "الحصة الثالثة عشرة", "Bagian 13", "15"),
                $this->data_tema("1", "13", "14", "15", "الحصة الرابعة عشرة", "Bagian 14", "15"),
                $this->data_tema("1", "14", "15", "16", "الحصة الخامسة عشرة", "Bagian 15", "15"),
                $this->data_tema("1", "15", "16", "17", "الحصة السادسة عشرة", "Bagian 16", "15"),
                $this->data_tema("1", "16", "17", "18", "الحصة السابعة عشرة", "Bagian 17", "15"),
                $this->data_tema("1", "17", "18", "19", "الحصة الثامنة عشرة", "Bagian 18", "15"),
                $this->data_tema("1", "18", "19", "20", "المحفوظات ١", "Bagian 19", "12"),
                $this->data_tema("1", "19", "20", "21", "المحفوظات ٢", "Bagian 20", "12"),
                $this->data_tema("1", "20", "21", "22", "المحفوظات ٣", "Bagian 21", "11"),
                $this->data_tema("1", "21", "22", "23", "المحفوظات ٤", "Bagian 22", "9"),
                $this->data_tema("1", "22", "23", "24", "المحفوظات ٥", "Bagian 23", "11"),
                $this->data_tema("1", "23", "24", "", "المحفوظات ٦", "Bagian 24", "8"),
                
            ];

            return $data;
        }

        public function data_tema($buku, $back, $id, $next, $tema, $tema_in, $count){
            $data = [
                "buku" => $buku,
                "back" => $back,
                "id" => $id,
                "next" => $next,
                "tema" => $tema,
                "tema_in" => $tema_in,
                "count" => $count
            ];

            return $data;
        }
    }
?>